# ========== GENERAL ==========
server.port=9091
app.baseUrl=http://localhost:9091

# ========== JPA ==========
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# ========== MARIADB DATABASE ==========
spring.datasource.url=jdbc:mariadb://mariadb:3306/dinedrop
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ========== H2 CONSOLE ==========
spring.h2.console.enabled=false